baseURL = "https://kane.mx/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "The Road"

theme = "dream-plus"

googleAnalytics = "UA-11561366-2"

pygmentsCodeFences = true
pygmentsUseClasses = false

enableRobotsTXT = true

#Enable Hugo Emoji Conversion
enableEmoji=true

enableGitInfo=true

[params]
	favicon = "/img/favicon.ico"

	#Cards or posts shown per page
	itemsPerPage = 4

	#Set whether you're hosting "cards" or "post"
	contentType = "posts"

	[params.utterances]
		repo = "zxkane/articles"
		issueTerm = "pathname"
		theme = "github-light"

	[params.author]
		name = "Kane"
		description = "Just a blog for personal experience or thoughts, mostly tech-related."
		avatar = "/img/portrait.jpg"
		motto = "Twin boys' father, open source mania."

	[params.features]
		#Enable Twitter Emoji
		twitterEmoji = true
		#Enable Table of Contents
		toc = false
		#Enable share card
		shareCard = true
		#Use custom CSS
		customCSS = ["/css/highlight.css"]

	[params.background]
		colorBG = false
		bgBlur = 0.4
		bgList = [
			"https://www.nasa.gov/sites/default/files/styles/full_width_feature/public/thumbnails/image/sunset.jpeg",
			"https://www.nasa.gov/sites/default/files/styles/full_width_feature/public/thumbnails/image/pia23059.jpg",
			"https://www.nasa.gov/sites/default/files/styles/full_width_feature/public/thumbnails/image/potw1912a.jpg",
			"https://www.nasa.gov/sites/default/files/styles/full_width_feature/public/thumbnails/image/stationmoon.jpg",
			"https://www.nasa.gov/sites/default/files/styles/full_width_feature/public/thumbnails/image/potw1911a.jpg",
			"https://www.nasa.gov/sites/default/files/styles/full_width_feature/public/thumbnails/image/3.3-445a2747.jpg"
			]

	#Tags settings
	[params.tags]
		enabled = true
		tagLimit = 10

	#Categories settings
	[params.categories]
		enabled = true

[social]
	email =  "me@kane.mx"
	github = "zxkane"
	stackoverflow = "390513/kane"
	siteStartYear = 2018

[sitemap]
	changefreq = "weekly"
	priority = 0.5