[[main]]
  name = "The Road"
  url = ""
  weight = -110

# Submenus are done this way: parent -> identifier
[[main]]
  name = "Links"
  identifier = "Links"
  weight = -108
[[main]]
  parent = "Links"
  name = "Effective Cloud Computing"
  url = "/series/effective-cloud-computing/"
  weight = 10
[[main]]
  parent = "Links"
  name = "Serverless"
  url = "/series/serverless-computing/"
  weight = 20
[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/zxkane"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/zxkane"
# [[social]]
#   name = "linkedin"
#   weight = 3
#   url = "https://www.linkedin.com/in/#"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
[[social]]
  weight = 3
  name = "stackoverflow"
  url = "https://stackoverflow.com/users/390513/kane"
# name = "gitlab"
# url = "https://gitlab.com/#"