name: github pages

on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - uses: actions/checkout@v2
        with:
          repository: zxkane/zxkane.github.io
          path: public/
          token: ${{ secrets.PAGES_DEPLOY_TOKEN }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.83.1'
          extended: true

      - name: Enable cw-rum
        run: | 
          echo '{{- partialCached "cw-rum" . }}' >> themes/hugo-clarity/layouts/partials/hooks/head-end.html
          
      - name: Build
        run: hugo --minify

      - name: Deploy
        run: |
          cd public/
          git config --global user.name 'Kane Zhu'
          git config --global user.email 'kane@users.noreply.github.com'
          git add .
          git commit -am "new release at `date`"
          git push