name: Link checker

on:
  push:
    branches:
      - '**'
  schedule:
    # Every Monday at 2:00 AM.
    - cron: '0 2 * * MON'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Report broken links
        uses: urlstechie/urlchecker-action@master
        with:
          # A comma-separated list of file types to cover in the URL checks
          file_types: md,toml,yml,scss
          # The timeout seconds to provide to requests, defaults to 5 seconds
          timeout: 30
          # How many times to retry a failed request (each is logged, defaults to 1)
          retry_count: 1
          # Choose whether to include files with no URLs in the output
          print_all: false
          # A comma separated patterns to exclude during URL checks
          exclude_patterns: http://www.w3.org,http://schema.org/,http://purl.org,http://ogp.me,http://rdfs.org,http://xmlns.com,http://localhost:1313/
